version: "3.4"

services:
  mr_lvl5_mission2:
    image: git.sethsamuel.online/fluffy/mission_ready_lvl5_mission2
    networks:
      - internal_interconnect_network
    deploy:
      placement:
        constraints:
          - node.hostname==vps
    volumes:
    - envVar:/app/back/.env:ro
    - serviceKey.json:/app/back/secrets/serviceKey.json:ro
networks:
  internal_interconnect_network:
    external: true
volumes:
  envVar:
    driver_opts:
      type: nfs
      o: "addr=srv.fluffyb.net,rw"
      device: "://dockerStorage/missionReadyLvl5/mission1/.env"
  serviceKey.json:
    driver_opts:
      type: nfs
      o: "addr=srv.fluffyb.net,rw"
      device: ":/dockerStorage/missionReadyLvl5/mission1/serviceKey.json:"