# Use an Nginx image for serving the built app
FROM node:lts-alpine
# copy backend over 
COPY ./backend /app/back

# install node and dependencies
WORKDIR /app/back
RUN npm ci --omit=dev 



# Expose the port
EXPOSE 4000
# Start Container
ENTRYPOINT ["node","/app/back/server.js"]