 echo "4dr:" $(grep -c 4dr csv.csv)
 echo "SUV:" $(grep -c SUV csv.csv)
 echo "2dr:" $(grep -c 2dr csv.csv)
 echo "Convertible:" $(grep -c Convertible csv.csv)
 echo "Station Wagon:" $(grep -c "Station\ Wagon" csv.csv)
 echo "Pickup:" $(grep -c Pickup csv.csv)
 echo "Van:" $(grep -c Van csv.csv)
 echo "3dr:" $(grep -c 3dr csv.csv)
---------------------------------------------
 echo "Acura:" $(grep -c Acura csv.csv)
 echo "Alfa Romeo:" $(grep -c "Alfa\ Romeo" csv.csv)
 echo "Aston Martin:" $(grep -c "Aston\ Martin" csv.csv)
 echo "Audi:" $(grep -c Audi csv.csv)
 echo "Bentley:" $(grep -c Bentley csv.csv)
 echo "BMW:" $(grep -c BMW csv.csv)
 echo "Buick:" $(grep -c Buick csv.csv)
 echo "Cadillac:" $(grep -c Cadillac csv.csv)
 echo "Chevrolet:" $(grep -c Chevrolet csv.csv)
 echo "Chrysler:" $(grep -c Chrysler csv.csv)
 echo "Dodge:" $(grep -c Dodge csv.csv)
 echo "Ferrari:" $(grep -c Ferrari csv.csv)
 echo "FIAT:" $(grep -c FIAT csv.csv)
 echo "Ford:" $(grep -c Ford csv.csv)
 echo "Genesis:" $(grep -c Genesis csv.csv)
 echo "GMC:" $(grep -c GMC csv.csv)
 echo "Honda:" $(grep -c Honda csv.csv)
 echo "Hyundai:" $(grep -c Hyundai csv.csv)
 echo "INFINITI:" $(grep -c INFINITI csv.csv)
 echo "Jaguar:" $(grep -c Jaguar csv.csv)
 echo "Jeep:" $(grep -c Jeep csv.csv)
 echo "Kia:" $(grep -c Kia csv.csv)
 echo "Lamborghini:" $(grep -c Lamborghini csv.csv)
 echo "Land Rover:" $(grep -c "Land\ Rover" csv.csv)
 echo "Lexus:" $(grep -c Lexus csv.csv)
 echo "Lincoln:" $(grep -c Lincoln csv.csv)
 echo "Maserati:" $(grep -c Maserati csv.csv)
 echo "Mazda:" $(grep -c Mazda csv.csv)
 echo "McLaren:" $(grep -c McLaren csv.csv)
 echo "Mercedes-Benz:" $(grep -c Mercedes-Benz csv.csv)
 echo "MINI:" $(grep -c MINI csv.csv)
 echo "Mitsubishi:" $(grep -c Mitsubishi csv.csv)
 echo "Nissan:" $(grep -c Nissan csv.csv)
 echo "Porsche:" $(grep -c Porsche csv.csv)
 echo "Ram:" $(grep -c Ram csv.csv)
 echo "Rolls-Royce:" $(grep -c Rolls-Royce csv.csv)
 echo "smart:" $(grep -c smart csv.csv)
 echo "Subaru:" $(grep -c Subaru csv.csv)
 echo "Tesla:" $(grep -c Tesla csv.csv)
 echo "Toyota:" $(grep -c Toyota csv.csv)
 echo "Volkswagen:" $(grep -c Volkswagen csv.csv)
 echo "Volvo:" $(grep -c Volvo csv.csv)