 echo "4dr:" $(grep -c 4dr csv.csv)
 echo "Convertible:" $(grep -c Convertible csv.csv)
 echo "SUV:" $(grep -c SUV csv.csv)
 echo "2dr:" $(grep -c 2dr csv.csv)
 echo "Pickup:" $(grep -c Pickup csv.csv)
echo "---------------------------------------------"
 echo "Audi:" $(grep -c Audi csv.csv)
 echo "BMW:" $(grep -c BMW csv.csv)
 echo "Chevrolet:" $(grep -c Chevrolet csv.csv)
 echo "Ford:" $(grep -c Ford csv.csv)
 echo "Nissan:" $(grep -c Nissan csv.csv)
 echo "Porsche:" $(grep -c Porsche csv.csv)
 echo "Subaru:" $(grep -c Subaru csv.csv)
 echo "Toyota:" $(grep -c Toyota csv.csv)
 echo "Volkswagen:" $(grep -c Volkswagen csv.csv)