name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_frontend_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy frontend Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy frontend
        id: builddeployFront
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FIELD_0EC524700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  #back end is seperate job to keep my keys away from azure 
  build_backend:
    name: Build and Deploy Backend job
    runs-on: ubuntu-latest
    environment: selfHost
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: git.sethsamuel.online
          # Username used to log against the Docker registry
          username: docker
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_REPO_KEY }}
          # Specifies whether the given registry is ECR (auto, true or false)
          # Log out from the Docker registry at the end of a job
          logout: true 
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          # Path to the Dockerfile
          file: ./deploy/Dockerfile.back
          # Push is a shorthand for --output=type=registry
          push: true # optional, default is false
          # List of tags
          tags: git.sethsamuel.online/fluffy/mission_ready_lvl5_mission2

  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs: [build_backend]
    environment: SelfHost
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_KEY }}

      - name: 'Stack Deploy'
        uses: cssnr/stack-deploy-action@v1
        with:
          name: 'mission_ready_mission2'
          file: './docker/docker-compose.yml'
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          ssh_key: '${{ secrets.DOCKER_SSH_KEY }}'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FIELD_0EC524700 }}
          action: "close"
          app_location: "/frontend" # Required input, set to your app's source code path
